// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application'

import HelloController from './hello_controller'
import Notification from '@stimulus-components/notification'
import CollapsibleController from './collapsible_controller'
import DropdownController from '@stimulus-components/dropdown'
import SelectorController from './selector_controller'
import MultiSelectController from './multi_select_controller'

application.register('hello', HelloController)
application.register('notification', Notification)
application.register('collapsible', CollapsibleController)
application.register('dropdown', DropdownController)
application.register('selector', SelectorController)
application.register('multi-select', MultiSelectController)
